---
- hosts: rhel-agents
  tasks:
    - name: Install python 3 and pip3
      yum:
        name:
          - python3
          - libselinux-python
        state: present

    - name: Install SELinux for Python 3
      pip:
        name:
          - selinux
        state: present
        executable: pip3
      vars:
        ansible_python_interpreter: /usr/bin/python3