- name: Agent check
  hosts: jenkins-agent
  become: yes
  tasks:
    - name: enable and start firewalld service
      systemd:
        name: firewalld
        state: started
        enabled: yes
    - name: permit traffic in default zone on port 22/tcp
      ansible.posix.firewalld:
        port: 22/tcp
        permanent: yes
        state: enabled
        immediate: yes